In [1]:
import torch
print(torch.__version__)

2.2.0


In [2]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

print(A.shape)
print(B.shape)

torch.Size([2, 2])
torch.Size([2, 2])


## Operations on Matrices

In [3]:
# A * B
# A - B
# A / B
# (2 * A) + (3 * B )

torch.add(A, B)

tensor([[ 6,  8],
        [10, 12]])

In [4]:
# torch.mul(A, B)
# A * B

print(torch.matmul(A, B))

print("-" * 20)

print(torch.matmul(B, A))

print("-" * 20)

print( A @ B )

tensor([[19, 22],
        [43, 50]])
--------------------
tensor([[23, 34],
        [31, 46]])
--------------------
tensor([[19, 22],
        [43, 50]])


## Transpose

In [5]:
print(B)

print( B.T )

print("-" * 20)

print( B.T @ A )

tensor([[5, 6],
        [7, 8]])
tensor([[5, 7],
        [6, 8]])
--------------------
tensor([[26, 38],
        [30, 44]])


In [6]:
A = torch.rand(2, 3)
B = torch.rand(2, 3)

print(A.shape)
print(B.shape)

print(B.T.shape)

# (2, 3) @ (3, 2) -> (2, 2)
print( A @ B.T )

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[0.2086, 0.5702],
        [0.1789, 0.2442]])


## Matrix Mean/Sum/Min/Max

In [7]:
A = torch.rand(2, 3)
print(A)
print(torch.mean(A))

print(torch.sum(A))

print(torch.max(A))
print(torch.min(A))

tensor([[0.2968, 0.1101, 0.5056],
        [0.8720, 0.1385, 0.8669]])
tensor(0.4650)
tensor(2.7900)
tensor(0.8720)
tensor(0.1101)


## Determinant of Matrix

In [8]:
A = torch.rand(3, 3)
print(A)

print(torch.det(A))

tensor([[0.6267, 0.4338, 0.1316],
        [0.6680, 0.0776, 0.6708],
        [0.9205, 0.2084, 0.2495]])
tensor(0.1290)


## Inverse of a matrix

In [9]:
A = torch.rand(3, 3)
print(A)

print(torch.inverse(A))

tensor([[4.0585e-01, 2.5071e-01, 4.1921e-01],
        [4.3546e-01, 4.1915e-01, 4.5890e-04],
        [9.2085e-01, 6.6889e-01, 4.2843e-01]])
tensor([[-13.1743, -12.7134,  12.9043],
        [ 13.6793,  15.5906, -13.4015],
        [  6.9592,   2.9845,  -4.4785]])


## Identity matrix

In [10]:
A = torch.eye(3)
B = torch.rand(3, 3)

print(B)
print(A)

print("-" * 20)

print( B @ A )

tensor([[0.9381, 0.9136, 0.7003],
        [0.3530, 0.0805, 0.4737],
        [0.0297, 0.2644, 0.0910]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
--------------------
tensor([[0.9381, 0.9136, 0.7003],
        [0.3530, 0.0805, 0.4737],
        [0.0297, 0.2644, 0.0910]])


## creating range of values

In [11]:
# python vs torch
print(list(range(10)))

print(torch.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Moving tensor to GPU

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([1, 2, 3]).to(device)
x = x.cpu()
x = torch.tensor([1, 2, 3], device=device)

print(x)

# Multi-GPU scenario
# tensor([1, 2, 3], device='cuda:0')
# tensor([1, 2, 3], device='cuda:1')
# tensor([1, 2, 3], device='cuda:2')

tensor([1, 2, 3])


## AutoGrad and Gradients
- at x = 2, y=(2)^2+3(2)+1=11
- `grad_fn` = means pytorch remembers how `y` was computed
- the process of `squaring = PowBackward0` and `addition = AddBackward0` is called the `computational graph`

In [20]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor(2.0, dtype=torch.float32, device=device, requires_grad=True)
y = (x ** 2) + (3 * x) + 1
print(y)

tensor(11., grad_fn=<AddBackward0>)


##
- dy/dx = 2x + 3
- dy/dx at x = 2 => 2(2) + 3 = 7

In [21]:
# compute the  gradient of y with respect to x
y.backward()

# access the gradient
print(x.grad)

tensor(7.)


## A straight line
start off with m = 0.01, c = 0.0 (call this model weights, hyperparameters)
- y = mx + c, 
- optimal values  m = 2, c = 10
- final equation: age = 2x + 10

In [ ]:
y = 0.5
y_pred = 0.8
loss = (y_pred - y) ** 2
print(f"Loss: {loss:.2f}")

Loss: 0.09


In [43]:
y = [0.5, 0.6, 0.7]
y_pred = [0.8, 0.9, 1.0]

# list(zip(y_pred, y))

for yp, y in zip(y_pred, y):
    print(f"yp: {yp}, y: {y}")

yp: 0.8, y: 0.5
yp: 0.9, y: 0.6
yp: 1.0, y: 0.7


In [ ]:
y = [0.5, 0.6, 0.7]
[x * 2 for x in y]

[0.5, 0.6, 0.7]

In [39]:
y = [0.5, 0.6, 0.7]
y_pred = [0.8, 0.9, 1.0]
loss = 1/len(y) * sum((yp - y) ** 2 for yp, y in zip(y_pred, y))
print(f"Loss: {loss:.2f}")

Loss: 0.09


In [49]:
torch.pow(torch.tensor(4.0), 2)

tensor(16.)

In [50]:
loss = torch.mean((torch.tensor(y_pred) - torch.tensor(y)) ** 2)
print(f"Loss: {loss:.2f}")


loss = torch.pow(torch.mean((torch.tensor(y_pred) - torch.tensor(y))), 2)
print(f"Loss: {loss:.2f}")

Loss: 0.09
Loss: 0.09


In [ ]:
# y = mx. y = age, x = height
# y = -2x

x = torch.tensor(1.0)
y = torch.tensor(2.0)

m = torch.tensor(1.0, requires_grad=True)

y_pred = m * x

#
# loss = (y_pred - y) ** 2
loss = (m * x - y) ** 2

# dloss/dm = 2 * (mx - y) * x

print(f"Loss: {loss:.2f}")

# backpropagation / backward pass to compute the gradient of loss with respect to m (dLoss/dm)
loss.backward()

# access the gradient
print(m.grad)

Loss: 1.00
tensor(-2.)


## Keep updating weights
- In machine learning; we choose the learning by choice `learning_rate = 0.05, 0.01, 0.5, 0.00023`
- `m = m - learning_rate * dm`
- dm = m.grad