In [231]:
import torch

In [232]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [233]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print(f"Using {device} device")

Using cpu device


## Inheritance

In [234]:
# parent class

class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} says hello!"

# child class
class Dog(Animal):
    def bark(self):
        return f"{self.name} says woof!"

class Cat(Animal):
    def meow(self):
        return f"{self.name} says meow!"


# create an instance of the Dog class
dog1 = Dog("Buddy")
cat1 = Cat("Whiskers")

print(dog1.bark())
print(dog1.speak())
print(dog1.name)

print("---")

print(cat1.meow())
print(cat1.speak())
print(cat1.name)

Buddy says woof!
Buddy says hello!
Buddy
---
Whiskers says meow!
Whiskers says hello!
Whiskers


## `super()` - is used to access methods and attributes from the parent class
 - `__init__()` the child class is calling the parent class constructor
 - Independent variables/ Predictors / Features (X)
 - Dependent variables / Response / Label / Target (y)
 - `y=mx+b` b is the bias variable

In [235]:
class LinearRegression(nn.Module):
    def __init__(self, input_size=1, output_size=1):
        super(LinearRegression, self).__init__()

        # 1 input feature, 1 output feature
        self.linear = nn.Linear(input_size, output_size) # y = wx + b

    def forward(self, x):
        return self.linear(x)

In [236]:
# create an instance of the LinearRegression class
model = LinearRegression().to(device)
print(model)

for param in model.parameters():
    print(param.data)

LinearRegression(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
tensor([[0.3669]])
tensor([-0.1811])


In [237]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.3669]], requires_grad=True), Parameter containing:
tensor([-0.1811], requires_grad=True)]


## Define out data

- normalization makes the data centered around the mean (sigma) falls between -1.0 and 1.0

In [238]:
weight = torch.tensor([[140], [155], [159], [179], [192], [200], [212]]).float()
height = torch.tensor([[60],  [62],  [67],  [70],  [71],  [72],  [75]]).float()

w_mean = weight.mean() # mean is the average value of the data
w_std = weight.std() # standard deviation is a measure of how spread out the data is
print(f"Weight mean: {w_mean:.2f}, std: {w_std:.2f}")

h_mean = height.mean()
h_std = height.std()
print(f"Height mean: {h_mean:.2f}, std: {h_std:.2f}")

# normalize the data
# weight = (weight - weight.mean()) / weight.std()
# height = (height - height.mean()) / height.std()


print("--- Normalized data ---")
print(weight)
print(height)

print(weight.shape)
print(height.shape)

Weight mean: 176.71, std: 26.33
Height mean: 68.14, std: 5.46
--- Normalized data ---
tensor([[140.],
        [155.],
        [159.],
        [179.],
        [192.],
        [200.],
        [212.]])
tensor([[60.],
        [62.],
        [67.],
        [70.],
        [71.],
        [72.],
        [75.]])
torch.Size([7, 1])
torch.Size([7, 1])


## Loss and Optimizer

In [239]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.000005)

## Training Loop

In [240]:
epochs = 10000

for epoch in range(epochs):
    model.train() # set the model to training mode

    # forward pass
    y_pred = model(weight.float()) # make predictions using the model

    # calculate loss
    loss = loss_fn(y_pred, height.float()) # calculate the loss between the predicted and actual values

    # backward pass
    loss.backward() # calculate the gradients dw and db

    # update weights
    optimizer.step() # w = w - lr * dw

    # zero gradients
    optimizer.zero_grad() # set the gradients to zero after updating weights

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.4f}")

Epoch 0: Loss = 30.4225
Epoch 100: Loss = 22.0495


Epoch 200: Loss = 22.0487
Epoch 300: Loss = 22.0480
Epoch 400: Loss = 22.0472
Epoch 500: Loss = 22.0464
Epoch 600: Loss = 22.0457
Epoch 700: Loss = 22.0449
Epoch 800: Loss = 22.0442
Epoch 900: Loss = 22.0434
Epoch 1000: Loss = 22.0427
Epoch 1100: Loss = 22.0419
Epoch 1200: Loss = 22.0411
Epoch 1300: Loss = 22.0404
Epoch 1400: Loss = 22.0396
Epoch 1500: Loss = 22.0389
Epoch 1600: Loss = 22.0381
Epoch 1700: Loss = 22.0373
Epoch 1800: Loss = 22.0366
Epoch 1900: Loss = 22.0359
Epoch 2000: Loss = 22.0351
Epoch 2100: Loss = 22.0343
Epoch 2200: Loss = 22.0336
Epoch 2300: Loss = 22.0328
Epoch 2400: Loss = 22.0320
Epoch 2500: Loss = 22.0313
Epoch 2600: Loss = 22.0305
Epoch 2700: Loss = 22.0298
Epoch 2800: Loss = 22.0290
Epoch 2900: Loss = 22.0283
Epoch 3000: Loss = 22.0275
Epoch 3100: Loss = 22.0268
Epoch 3200: Loss = 22.0260
Epoch 3300: Loss = 22.0253
Epoch 3400: Loss = 22.0245
Epoch 3500: Loss = 22.0237
Epoch 3600: Loss = 22.0230
Epoch 3700: Loss = 22.0222
Epoch 3800: Loss = 22.0215
Epoch 390

## Make Prediction

In [241]:
for param in model.parameters():
    print(param.data)

tensor([[0.3828]])
tensor([-0.1195])


`height = 0.9649 * weight -8.3498e-07`

In [242]:
test = torch.tensor([[180]])
predicted_height = model(test.float())
print(f"Predicted height for weight 180: {predicted_height.item():.2f}")

Predicted height for weight 180: 68.79


In [243]:
# reverse the normalization
# predicted_height = (predicted_height * h_std) + h_mean
# print(f"Predicted height for weight 180 (reverse normalized): {predicted_height.item():.2f}")